framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: ~

    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true
