index:
    path: /
    controller: App\Controller\HomeController::home

home:
    path: /home
    controller: App\Controller\HomeController::home

user-login:
    path: /login
    controller: App\Controller\AuthController::login

user-register:
    path: /register
    controller: App\Controller\AuthController::register

user-logout:
    path: /logout
    methods: GET

generate-invoice:
    path: /invoice/generate
    controller: App\Controller\InvoiceController::generateInvoice

contractor-list:
    path: /contractor/list
    controller: App\Controller\ContractorController::list

contractor-create:
    path: /contractor/create
    controller: App\Controller\ContractorController::create

contractor-edit:
    path: /contractor/{idContractor}/edit
    controller: App\Controller\ContractorController::edit

contractor-change-status:
    path: /contractor/{idContractor}/status/change
    controller: App\Controller\ContractorController::changeStatus

document-create:
    path: /document/create
    controller: App\Controller\DocumentController::create

document-list:
    path: /document/list
    controller: App\Controller\DocumentController::list

document-delete:
    path: /document/{idDocument}/delete
    controller: App\Controller\DocumentController::delete

document-preview:
    path: /document/{idDocument}/preview
    controller: App\Controller\DocumentController::preview

document-download:
    path: /document/{idDocument}/download
    controller: App\Controller\DocumentController::download
